CREATE TABLE IF NOT EXISTS public.qbo_items (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    name TEXT,
    description TEXT,
    active BOOLEAN,
    sub_item BOOLEAN,
    fully_qualified_name TEXT,
    taxable BOOLEAN,
    sales_tax_included BOOLEAN,
    unit_price NUMERIC(15, 2),
    type TEXT,
    level INTEGER,
    purchase_desc TEXT,
    purchase_tax_included BOOLEAN,
    purchase_cost NUMERIC(15, 2),
    track_qty_on_hand BOOLEAN,
    qty_on_hand NUMERIC(15, 2),
    inv_start_date DATE,
    sku TEXT,
    service_type TEXT,
    item_category_type TEXT,
    asset_account_ref TEXT,
    expense_account_ref TEXT,
    income_account_ref TEXT,
    sales_tax_code_ref TEXT,
    parent_ref TEXT,
    purchase_tax_code_ref TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
