CREATE TABLE IF NOT EXISTS public.qbo_company_info (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    company_name TEXT,
    legal_name TEXT,
    company_start_date DATE,
    fiscal_year_start_month TEXT,
    country TEXT,
    supported_languages TEXT,
    default_time_zone TEXT,
    primary_phone TEXT,
    email TEXT,
    web_addr TEXT,
    company_addr_line1 TEXT,
    company_addr_line2 TEXT,
    company_addr_city TEXT,
    company_addr_state TEXT,
    company_addr_postal_code TEXT,
    company_addr_country TEXT,
    legal_addr_line1 TEXT,
    legal_addr_line2 TEXT,
    legal_addr_city TEXT,
    legal_addr_state TEXT,
    legal_addr_postal_code TEXT,
    legal_addr_country TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
