CREATE TABLE IF NOT EXISTS public.qbo_vendors (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    title TEXT,
    given_name TEXT,
    middle_name TEXT,
    family_name TEXT,
    suffix TEXT,
    company_name TEXT,
    display_name TEXT,
    print_on_check_name TEXT,
    active BOOLEAN,
    tax_identifier TEXT,
    balance NUMERIC(15, 2),
    bill_rate NUMERIC(15, 2),
    acct_num TEXT,
    vendor_1099 BOOLEAN,
    tax_reporting_basis TEXT,
    primary_phone TEXT,
    alternate_phone TEXT,
    mobile TEXT,
    fax TEXT,
    primary_email TEXT,
    web_addr TEXT,
    term_ref TEXT,
    ap_account_ref TEXT,
    currency_code TEXT,
    currency_name TEXT,
    bill_addr_line1 TEXT,
    bill_addr_line2 TEXT,
    bill_addr_city TEXT,
    bill_addr_state TEXT,
    bill_addr_postal_code TEXT,
    bill_addr_country TEXT,
    v4_id_pseudonym TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
