CREATE TABLE IF NOT EXISTS public.qbo_invoices (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    doc_number TEXT,
    txn_date DATE,
    due_date DATE,
    ship_date DATE,
    private_note TEXT,
    total_amt NUMERIC(15, 2),
    balance NUMERIC(15, 2),
    deposit NUMERIC(15, 2),
    home_total_amt NUMERIC(15, 2),
    home_balance NUMERIC(15, 2),
    exchange_rate NUMERIC(15, 6),
    apply_tax_after_discount BOOLEAN,
    print_status TEXT,
    email_status TEXT,
    global_tax_calculation TEXT,
    invoice_link TEXT,
    e_invoice_status TEXT,
    tracking_num TEXT,
    free_form_address BOOLEAN,
    allow_online_payment BOOLEAN,
    allow_ipn_payment BOOLEAN,
    allow_online_credit_card_payment BOOLEAN,
    allow_online_ach_payment BOOLEAN,
    customer_ref TEXT,
    customer_name TEXT,
    department_ref TEXT,
    sales_term_ref TEXT,
    ship_method_ref TEXT,
    tax_exemption_ref TEXT,
    currency_code TEXT,
    currency_name TEXT,
    bill_addr_line1 TEXT,
    bill_addr_line2 TEXT,
    bill_addr_city TEXT,
    bill_addr_state TEXT,
    bill_addr_postal_code TEXT,
    bill_addr_country TEXT,
    ship_addr_line1 TEXT,
    ship_addr_line2 TEXT,
    ship_addr_city TEXT,
    ship_addr_state TEXT,
    ship_addr_postal_code TEXT,
    ship_addr_country TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
