CREATE TABLE IF NOT EXISTS public.qbo_employees (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    given_name TEXT,
    middle_name TEXT,
    family_name TEXT,
    suffix TEXT,
    display_name TEXT,
    print_on_check_name TEXT,
    employee_number TEXT,
    title TEXT,
    bill_rate NUMERIC(15, 2),
    cost_rate NUMERIC(15, 2),
    birth_date DATE,
    gender TEXT,
    hired_date DATE,
    released_date DATE,
    active BOOLEAN,
    organization BOOLEAN,
    billable_time BOOLEAN,
    primary_phone TEXT,
    mobile TEXT,
    email TEXT,
    primary_addr_line1 TEXT,
    primary_addr_line2 TEXT,
    primary_addr_city TEXT,
    primary_addr_state TEXT,
    primary_addr_postal_code TEXT,
    primary_addr_country TEXT,
    v4_id_pseudonym TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
