CREATE TABLE IF NOT EXISTS public.qbo_customers (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    title TEXT,
    given_name TEXT,
    middle_name TEXT,
    family_name TEXT,
    suffix TEXT,
    fully_qualified_name TEXT,
    company_name TEXT,
    display_name TEXT,
    print_on_check_name TEXT,
    notes TEXT,
    active BOOLEAN,
    is_project BOOLEAN,
    job BOOLEAN,
    bill_with_parent BOOLEAN,
    taxable BOOLEAN,
    balance NUMERIC(15, 2),
    balance_with_jobs NUMERIC(15, 2),
    preferred_delivery_method TEXT,
    resale_num TEXT,
    level INTEGER,
    open_balance_date DATE,
    primary_tax_identifier TEXT,
    bill_addr_line1 TEXT,
    bill_addr_line2 TEXT,
    bill_addr_city TEXT,
    bill_addr_state TEXT,
    bill_addr_postal_code TEXT,
    bill_addr_country TEXT,
    ship_addr_line1 TEXT,
    ship_addr_line2 TEXT,
    ship_addr_city TEXT,
    ship_addr_state TEXT,
    ship_addr_postal_code TEXT,
    ship_addr_country TEXT,
    primary_phone TEXT,
    alternate_phone TEXT,
    mobile TEXT,
    fax TEXT,
    primary_email TEXT,
    web_addr TEXT,
    default_tax_code_ref TEXT,
    sales_term_ref TEXT,
    payment_method_ref TEXT,
    parent_ref TEXT,
    ar_account_ref TEXT,
    currency_code TEXT,
    currency_name TEXT,
    client_entity_id TEXT,
    v4_id_pseudonym TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);

CREATE INDEX IF NOT EXISTS idx_qbo_customers_display_name
    ON public.qbo_customers (display_name);

CREATE INDEX IF NOT EXISTS idx_qbo_customers_active
    ON public.qbo_customers (active);
