CREATE TABLE IF NOT EXISTS public.qbo_bills (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    due_date DATE,
    balance NUMERIC(15, 2),
    total_amt NUMERIC(15, 2),
    txn_date DATE,
    doc_number TEXT,
    private_note TEXT,
    exchange_rate NUMERIC(15, 6),
    global_tax_calculation TEXT,
    sales_term_ref TEXT,
    vendor_ref TEXT,
    vendor_name TEXT,
    department_ref TEXT,
    ap_account_ref TEXT,
    currency_code TEXT,
    currency_name TEXT,
    vendor_addr_line1 TEXT,
    vendor_addr_line2 TEXT,
    vendor_addr_city TEXT,
    vendor_addr_state TEXT,
    vendor_addr_postal_code TEXT,
    vendor_addr_country TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
