CREATE TABLE IF NOT EXISTS public.qbo_estimates (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    doc_number TEXT,
    txn_date DATE,
    txn_status TEXT,
    private_note TEXT,
    total_amt NUMERIC(15, 2),
    exchange_rate NUMERIC(15, 6),
    apply_tax_after_discount BOOLEAN,
    print_status TEXT,
    email_status TEXT,
    due_date DATE,
    ship_date DATE,
    expiration_date DATE,
    accepted_by TEXT,
    accepted_date DATE,
    global_tax_calculation TEXT,
    customer_ref TEXT,
    customer_name TEXT,
    project_ref TEXT,
    department_ref TEXT,
    class_ref TEXT,
    sales_term_ref TEXT,
    ship_method_ref TEXT,
    tracking_num TEXT,
    free_form_address BOOLEAN,
    currency_code TEXT,
    currency_name TEXT,
    bill_addr_line1 TEXT,
    bill_addr_line2 TEXT,
    bill_addr_city TEXT,
    bill_addr_state TEXT,
    bill_addr_postal_code TEXT,
    bill_addr_country TEXT,
    ship_addr_line1 TEXT,
    ship_addr_line2 TEXT,
    ship_addr_city TEXT,
    ship_addr_state TEXT,
    ship_addr_postal_code TEXT,
    ship_addr_country TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
