CREATE TABLE IF NOT EXISTS public.qbo_payments (
    qbo_id TEXT PRIMARY KEY,
    sync_token TEXT,
    payment_ref_num TEXT,
    total_amt NUMERIC(15, 2),
    unapplied_amt NUMERIC(15, 2),
    exchange_rate NUMERIC(15, 6),
    txn_date DATE,
    txn_source TEXT,
    private_note TEXT,
    txn_status TEXT,
    transaction_location_type TEXT,
    process_payment BOOLEAN,
    customer_ref TEXT,
    customer_name TEXT,
    ar_account_ref TEXT,
    payment_method_ref TEXT,
    deposit_to_account_ref TEXT,
    tax_exemption_ref TEXT,
    currency_code TEXT,
    currency_name TEXT,
    qbo_created_at TIMESTAMPTZ,
    qbo_updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    raw_data JSONB
);
